### ISSUE TITLE
Серая тема

### ISSUE THREAD

**Issue by googlioner** [tashik/OptionVictory#1]
Хотелось бы серую тему!
"Стандартные" вырвиглазные сильно кровоточат глаза! :)

**Comment by tashik** [comment]
> Хотелось бы серую тему!
> "Стандартные" вырвиглазные сильно кровоточат глаза! :)

Покажите пример того, чего Вы хотите

**Comment by tashik** [comment]
Сделала новую тему взамен Безумной. На сайте доступно обновление, версия ovic-2.2.2-dark
